### ISSUE TITLE
[MacOS Issue] Command Errors

### ISSUE THREAD

**Issue by IvanShires** [nathayoung/DataDashboard_Unix#2]
When run on Mac (10.14), there are errors present where several commands are not recognized including Rem, and several commands relating to connecting to the SQL server.

Attached is the log:
> Ivans-MacBook-Pro:DataDashboard_Unix 1vannn$ bash update.sh 
Checking Installs
update.sh: line 2: Rem: command not found
update.sh: line 3: Rem: command not found
update.sh: line 4: Rem: command not found
update.sh: line 5: Rem: command not found
update.sh: line 6: Rem: command not found
update.sh: line 7: Rem: command not found
update.sh: line 8: Rem: command not found
update.sh: line 9: Rem: command not found
update.sh: line 10: Rem: command not found
update.sh: line 11: Rem: command not found
update.sh: line 12: Rem: command not found
Check complete!
Updating Land...
Traceback (most recent call last):
  File "County_MedianListingPrice_AllHomes.py", line 127, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "County_MedianListingPricePerSqft_AllHomes.py", line 127, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "County_MedianValuePerSqft_AllHomes.py", line 127, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "County_Zhvi_AllHomes.py", line 127, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "GeoFRED_All_Transactions_House_Price_Index.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "GeoFRED_Homeownership_Rate_by_County.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "GeoFRED_New_Private_Housing_Structures.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
fatal: Paths with -a does not make sense.
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
remote: Permission to nathayoung/DataDashboard_Unix.git denied to ipshires1-catamount-wcu-edu.
fatal: unable to access 'https://github.com/nathayoung/DataDashboard_Unix.git/': The requested URL returned error: 403
Update complete!
Updating Demographics...
Updating Civilian Labor Force
Traceback (most recent call last):
  File "GeoFRED_Civilian_Labor_Force_by_County_Persons.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Updating EQFXSUBPRIME
Traceback (most recent call last):
  File "GeoFRED_EQFXSUBPRIME.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Updating Educated Peoples
Traceback (most recent call last):
  File "GeoFRED_People_25_Years_and_Over_Who_Have_Completed_an_Associates_Degree_or_Higher_5year_estimate_by_County_Percent.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
Updating Resident Population
Traceback (most recent call last):
  File "GeoFRED_Resident_Population_by_County_Thousands_of_Persons.py", line 96, in <module>
    autocommit=True)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
demographics.sh: line 11: cd: Updates: No such file or directory
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
remote: Permission to nathayoung/DataDashboard_Unix.git denied to ipshires1-catamount-wcu-edu.
fatal: unable to access 'https://github.com/nathayoung/DataDashboard_Unix.git/': The requested URL returned error: 403
Update complete!
Updating Labor...
(null): can't open file 'ScriptsCAINC5N_NC.py': [Errno 2] No such file or directory
(null): can't open file 'ScriptsCAINC6N_NC.py': [Errno 2] No such file or directory
(null): can't open file 'ScriptsGeoFRED_Civilian_Labor_Force_by_County_Persons.py': [Errno 2] No such file or directory
(null): can't open file 'ScriptsGeoFRED_People_25_Years_and_Over_Who_Have_Completed_an_Associates_Degree_or_Higher_5year_estimate_by_County_Percent.py': [Errno 2] No such file or directory
(null): can't open file 'ScriptsGeoFRED_Resident_Population_by_County_Thousands_of_Persons.py': [Errno 2] No such file or directory
(null): can't open file 'ScriptsGeoFRED_Unemployment_Rate_by_County_Percent.py': [Errno 2] No such file or directory
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
remote: Permission to nathayoung/DataDashboard_Unix.git denied to ipshires1-catamount-wcu-edu.
fatal: unable to access 'https://github.com/nathayoung/DataDashboard_Unix.git/': The requested URL returned error: 403
Update complete!
Update Earnings...
Nathan Young
Junior Data Analyst
Center for the Study of Free Enterprise
Traceback (most recent call last):
  File "Scripts/CAINC5N_NC.py", line 24, in <module>
    get_ipython().run_line_magic('load_ext', 'watermark')
NameError: name 'get_ipython' is not defined
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
fatal: Paths with -a does not make sense.
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
remote: Permission to nathayoung/DataDashboard_Unix.git denied to ipshires1-catamount-wcu-edu.
fatal: unable to access 'https://github.com/nathayoung/DataDashboard_Unix.git/': The requested URL returned error: 403
Update complete!

**Comment by nathayoung** [comment]
Issues should be fixed.
